dictionary:
    'eldenring' : 'Eldenring'
    'i am the senate': 'star_wars'
    'hello there': 'star_wars'
    'general kenobi': 'star_wars'
    'hello there general kenobi': 'star_wars'
    'jojo': 'JoJoMemes'
    'feed': ['JoJoMemes','star_wars', 'science']
books:
    'бушидо' : 'bushido.txt'
